AWSTemplateFormatVersion: 2010-09-09
Description: Code build
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  CodeBuildName:
    Description: User-defined code build name
    Type: String
    Default: f-iot-build
  DeployEnv:
    Type: String
    Default: dev

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildName
      Description: Build project for development environment.
      ServiceRole: !GetAtt ProjectRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0-22.03.15
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: S3_BUCKET_CFN_NAME
            Type: PARAMETER_STORE
            Value: !Sub /${DeployEnv}/s3/cfn/BucketName
          - Name: S3_BUCKET_LAMBDA_NAME
            Type: PARAMETER_STORE
            Value: !Sub /${DeployEnv}/s3/lambda/BucketName
      Source:
        Location: https://github.com/TomoyukiSugiyama/ElasticStack
        Type: GITHUB
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
            - Type: BASE_REF
              Pattern: refs/heads/develop
              ExcludeMatchedPattern: false
      SourceVersion: refs/heads/develop
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      TimeoutInMinutes: 10
  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Condition: {}
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: FIoTBuildDevPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildName}
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildName}:*
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${DeployEnv}/s3/cfn/BucketName
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${DeployEnv}/s3/lambda/BucketName
              - Effect: Allow
                Action:
                  - ecr:DescribeRepositories
                  - ecr:CompleteLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:InitiateLayerUpload
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                Resource:
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${DeployEnv}-repogitory
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::{{resolve:ssm:/${DeployEnv}/s3/lambda/BucketName:1}}/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::{{resolve:ssm:/${DeployEnv}/s3/cfn/BucketName:1}}/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::*codepipeline*
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource:
                  - "*"

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  CodeBuildName:
    Value: !Ref Project
