AWSTemplateFormatVersion: 2010-09-09
Description: Pre-build
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: f-iot
  S3CfnBucketParameterKey:
    Description: User-defined s3 cfn bucket parameter key
    Type: String
    Default: /s3/cfn/BucketName
  S3LambdaBucketParameterKey:
    Description: User-defined s3 lambda bucket parameter key
    Type: String
    Default: /s3/cfn/BucketName

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  CodeBuildDev:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: code-build.yaml
      Parameters:
        CodeBuildName: !Sub ${ProjectName}-build-dev
  CodePipelineDev:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: code-pipeline.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        BranchName: develop
        CodeBuildName: !GetAtt CodeBuildDev.Outputs.CodeBuildName
        CodePipelineName: !Sub ${ProjectName}-pipeline-dev

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  ProjectName:
    Value: !Ref ProjectName
