AWSTemplateFormatVersion: 2010-09-09
Description: Pre-build
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: f-iot
  DeployEnv:
    Type: String
    Default: dev

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  CodeBuildDev:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: code-build.yaml
      Parameters:
        CodeBuildName: !Sub ${ProjectName}-build-dev
        DeployEnv: !Ref DeployEnv
  CodePipelineDev:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: code-pipeline.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        BranchName: develop
        CodeBuildName: !GetAtt CodeBuildDev.Outputs.CodeBuildName
        CodePipelineName: !Sub ${ProjectName}-pipeline-dev
        DeployEnv: !Ref DeployEnv

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  ProjectName:
    Value: !Ref ProjectName
