version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.16

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build lambda
      - cd $CODEBUILD_SRC_DIR/provisioning/lambda
      - ./build.sh
      - $CODEBUILD_SRC_DIR/helper-scripts/s3-ops.sh push $S3_BUCKET_LAMBDA_NAME populate-alb-tg-with-opensearch/populate-alb-tg-with-opensearch.zip
      - echo Build container
      - cd $CODEBUILD_SRC_DIR/provisioning/ecs
      - ./deploy-container-image-to-ecr.sh
      - echo Build cloudformation
      - cd $CODEBUILD_SRC_DIR
      - $CODEBUILD_SRC_DIR/helper-scripts/cfn-stack-ops.sh package provisioning/cfn/elastic-stack.yaml $S3_BUCKET_CFN_NAME artifact.yaml
  post_build:
    commands:
      - echo Build completed on `date`
