version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      golang: 1.14
      ruby: 2.7
    commands:
      - export ECR_URI=$(aws ecr describe-repositories --repository-names f-iot-rep --query 'repositories[].repositoryUri' --output text)
      - pip install cfn-lint
      - gem install cfn-nag
      - brew install cloudformation-guard
      - chmod +x $CODEBUILD_SRC_DIR/provisioning/lambda/build.sh
      - chmod +x $CODEBUILD_SRC_DIR/provisioning/ecs/deploy-container-image-to-ecr.sh
      - chmod +x $CODEBUILD_SRC_DIR/provisioning/helper-scripts/s3-ops.sh
      - chmod +x $CODEBUILD_SRC_DIR/provisioning/helper-scripts/cfn-stack-ops.sh

  pre_build:
    on-failure: ABORT
    commands:
      - cfn-lint -t $CODEBUILD_SRC_DIR/provisioning/cfn/*
      - cfn_nag_scan --input-path $CODEBUILD_SRC_DIR/provisioning/cfn/
      - cd $CODEBUILD_SRC_DIR/cfn-guard-rules
      - ./run-cfn-guard.sh

  build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR/provisioning/lambda
      - ./build.sh
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/s3-ops.sh push $S3_BUCKET_LAMBDA_NAME populate-alb-tg-with-opensearch/populate-alb-tg-with-opensearch.zip
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/s3-ops.sh push $S3_BUCKET_LAMBDA_NAME detach-task-to-be-terminated-from-nlb/detach-task-to-be-terminated-from-nlb.zip
      - cd $CODEBUILD_SRC_DIR/provisioning/ecs
      - ./deploy-container-image-to-ecr.sh
      - cd $CODEBUILD_SRC_DIR
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/cfn-stack-ops.sh package provisioning/cfn/elastic-stack.yaml $S3_BUCKET_CFN_NAME artifact.yaml

  post_build:
    on-failure: ABORT
    commands:
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/s3-ops.sh push $S3_BUCKET_CFN_NAME artifact.yaml
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/cfn-stack-ops.sh validate $S3_BUCKET_CFN_NAME

artifacts:
  files:
    - artifact.yaml
