version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      golang: 1.14
      ruby: 2.6
    commands:
      - export ECR_URI=$(aws ecr describe-repositories --repository-names f-iot-rep --query 'repositories[].repositoryUri' --output text)
      - pip install cfn-lint
      - gem install cfn-nag
      - chmod +x $CODEBUILD_SRC_DIR/provisioning/lambda/build.sh
      - chmod +x $CODEBUILD_SRC_DIR/provisioning/ecs/deploy-container-image-to-ecr.sh
      - chmod +x $CODEBUILD_SRC_DIR/provisioning/helper-scripts/s3-ops.sh
      - chmod +x $CODEBUILD_SRC_DIR/provisioning/helper-scripts/cfn-stack-ops.sh

  build:
    on-failure: ABORT
    commands:
      - echo Build lambda
      - cd $CODEBUILD_SRC_DIR/provisioning/lambda
      - ./build.sh
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/s3-ops.sh push $S3_BUCKET_LAMBDA_NAME populate-alb-tg-with-opensearch/populate-alb-tg-with-opensearch.zip
      - echo Build container
      - cd $CODEBUILD_SRC_DIR/provisioning/ecs
      - ./deploy-container-image-to-ecr.sh
      - echo Build cloudformation
      - cd $CODEBUILD_SRC_DIR
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/cfn-stack-ops.sh package provisioning/cfn/elastic-stack.yaml $S3_BUCKET_CFN_NAME artifact.yaml

  post_build:
    on-failure: ABORT
    commands:
      - echo Upload artifact.yaml
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/s3-ops.sh push $S3_BUCKET_CFN_NAME artifact.yaml
      - echo Run cfn validation
      - $CODEBUILD_SRC_DIR/provisioning/helper-scripts/cfn-stack-ops.sh validate $S3_BUCKET_CFN_NAME
      - echo Run cfn-lint
      - cfn-lint -t $CODEBUILD_SRC_DIR/provisioning/cfn/*
      - echo Run cfn-nag_scan
      - cfn_nag_scan --input-path $CODEBUILD_SRC_DIR/provisioning/cfn/
