version: '3'

x-aws-vpc: ${AWS_VPC}

services:
  logstash:
    image: ${ECR_URI}:logstash
    container_name: worker
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4Gb
