AWSTemplateFormatVersion: "2010-09-09"
Description: Elastic Stack
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  VpcCidrBlock:
    Type: String
    Default: 172.31.0.0/16

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network.yaml
      Parameters:
        VpcCidrBlock: !Ref VpcCidrBlock

  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: security-group.yaml
      Parameters:
        VpcId: !GetAtt Network.Outputs.VpcId
        VpcCidrBlock: !Ref VpcCidrBlock

  SpringBoard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        KeyName: elastic-stack
        SubnetId: !GetAtt Network.Outputs.PublicSubnet1Id
        SecurityGroupId: !GetAtt SecurityGroup.Outputs.SecurityGroupId

  Opensearch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: opensearch.yaml
      Parameters:
        SubnetId: !GetAtt Network.Outputs.PrivateSubnet1Id
        SecurityGroupId: !GetAtt SecurityGroup.Outputs.OpenSearchSecurityGroupId

  VpcEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc-endpoint.yaml
      Parameters:
        VpcId: !GetAtt Network.Outputs.VpcId
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt Network.Outputs.PrivateSubnet1Id,
              !GetAtt Network.Outputs.PrivateSubnet2Id,
              !GetAtt Network.Outputs.PrivateSubnet3Id,
            ],
          ]
        SecurityGroupId: !GetAtt SecurityGroup.Outputs.FargateSecurityGroupId
        PrivateRouteTableId: !GetAtt Network.Outputs.PrivateRouteTableId

  Lambda:
    Type: AWS::CloudFormation::Stack
    DependsOn: AlbForOpensearch
    Properties:
      TemplateURL: lambda.yaml
      Parameters:
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt Network.Outputs.PrivateSubnet1Id,
              !GetAtt Network.Outputs.PrivateSubnet2Id,
              !GetAtt Network.Outputs.PrivateSubnet3Id,
            ],
          ]
        SecurityGroupId: !GetAtt SecurityGroup.Outputs.FargateSecurityGroupId
        DomainEndpoint: !GetAtt Opensearch.Outputs.DomainEndpoint
        AlbId: !GetAtt AlbForOpensearch.Outputs.AlbId
        AlbTargetGroupId: !GetAtt AlbForOpensearch.Outputs.AlbTargetGroupId

  LambdaBacked:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - Opensearch
      - VpcEndpoint
    Properties:
      TemplateURL: lambda-backed.yaml
      Parameters:
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt Network.Outputs.PrivateSubnet1Id,
              !GetAtt Network.Outputs.PrivateSubnet2Id,
              !GetAtt Network.Outputs.PrivateSubnet3Id,
            ],
          ]
        SecurityGroupId: !GetAtt SecurityGroup.Outputs.FargateSecurityGroupId

  # LogstashFargate:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: logstash-fargate.yaml
  #     Parameters:
  #       VpcId: !GetAtt Network.Outputs.VpcId
  #       SubnetIds:
  #         !Join [
  #           ",",
  #           [
  #             !GetAtt Network.Outputs.PrivateSubnet1Id,
  #             !GetAtt Network.Outputs.PrivateSubnet2Id,
  #             !GetAtt Network.Outputs.PrivateSubnet3Id,
  #           ],
  #         ]

  AlbForOpensearch:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaBacked
    Properties:
      TemplateURL: alb-for-opensearch.yaml
      Parameters:
        VpcId: !GetAtt Network.Outputs.VpcId
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt Network.Outputs.PrivateSubnet1Id,
              !GetAtt Network.Outputs.PrivateSubnet2Id,
              !GetAtt Network.Outputs.PrivateSubnet3Id,
            ],
          ]
        SecurityGroupId: !GetAtt SecurityGroup.Outputs.SecurityGroupId
        TargetIp: !GetAtt LambdaBacked.Outputs.IpAddr

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  VpcId:
    Value: !GetAtt Network.Outputs.VpcId
