AWSTemplateFormatVersion: "2010-09-09"
Description: Elastic Stack

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network.yaml
      Parameters:
        VpcCidrBlock: 172.31.0.0/16
