AWSTemplateFormatVersion: "2010-09-09"
Description: LambdaBacked

# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  SubnetIds:
    Type: String
  SecurityGroupId:
    Type: String
  DomainEndpoint:
    Type: String
# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------

Resources:
  RezolveFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: populate-alb-tg-with-opensearch-on-cfn
      Role: !GetAtt RezolveFunctionRole.Arn
      Code:
        S3Bucket: lambda-ces09iuin3ybh1kmv0fp-artifact
        S3Key: populate-alb-tg-with-opensearch-on-cfn.zip
      Runtime: go1.x
      Timeout: 5
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - Ref: SecurityGroupId
        SubnetIds: !Split [",", !Ref SubnetIds]

  RezolveFunctionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Condition: {}
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: FIoTElasticLoadBalancingAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "elasticloadbalancing:DescribeLoadBalancers"
                  - "elasticloadbalancing:DescribeTargetHealth"
                  - "elasticloadbalancing:DescribeTargetGroups"
                Resource: "*"
      Tags:
        - Key: com.trim.f-iot
          Value: lambda-backed
    Type: AWS::IAM::Role

  RezolveInfo:
    Type: Custom::RezolveInfo
    Properties:
      ServiceToken: !GetAtt RezolveFunction.Arn
      Region: !Ref "AWS::Region"
      DomainEndpoint: !Ref DomainEndpoint

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  IpAddr:
    Value: !GetAtt RezolveInfo.Addr
