AWSTemplateFormatVersion: 2010-09-09
Description: Logstash Fargate
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: String

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  CloudMap:
    Properties:
      Description: Service Map for Docker Compose project ecs
      Name: ecs.local
      Vpc: !Ref VpcId
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
  Cluster:
    Properties:
      ClusterName: ecs
      Tags:
        - Key: com.docker.compose.project
          Value: ecs
    Type: AWS::ECS::Cluster
  DefaultNetwork:
    Properties:
      GroupDescription: ecs Security Group for default network
      Tags:
        - Key: com.docker.compose.project
          Value: ecs
        - Key: com.docker.compose.network
          Value: ecs_default
      VpcId: !Ref VpcId
    Type: AWS::EC2::SecurityGroup
  DefaultNetworkIngress:
    Properties:
      Description: Allow communication within network default
      GroupId:
        Ref: DefaultNetwork
      IpProtocol: "-1"
      SourceSecurityGroupId:
        Ref: DefaultNetwork
    Type: AWS::EC2::SecurityGroupIngress
  LogGroup:
    Properties:
      LogGroupName: /docker-compose/ecs
    Type: AWS::Logs::LogGroup
  LogstashService:
    Properties:
      Cluster:
        Fn::GetAtt:
          - Cluster
          - Arn
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Ref: DefaultNetwork
          Subnets: !Split [",", !Ref SubnetIds]
      PlatformVersion: 1.4.0
      PropagateTags: SERVICE
      SchedulingStrategy: REPLICA
      ServiceRegistries:
        - RegistryArn:
            Fn::GetAtt:
              - LogstashServiceDiscoveryEntry
              - Arn
      Tags:
        - Key: com.docker.compose.project
          Value: ecs
        - Key: com.docker.compose.service
          Value: logstash
      TaskDefinition:
        Ref: LogstashTaskDefinition
    Type: AWS::ECS::Service
  LogstashServiceDiscoveryEntry:
    Properties:
      Description: '"logstash" service discovery entry in Cloud Map'
      DnsConfig:
        DnsRecords:
          - TTL: 60
            Type: A
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: logstash
      NamespaceId:
        Ref: CloudMap
    Type: AWS::ServiceDiscovery::Service
  LogstashTaskDefinition:
    Properties:
      ContainerDefinitions:
        - Command:
            - !Sub "${AWS::Region}.compute.internal"
            - ecs.local
          Essential: false
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/f-iot-rep:ecs-searchdomain-sidecar"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: LogGroup
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: ecs
          Name: Logstash_ResolvConf_InitContainer
        - DependsOn:
            - Condition: SUCCESS
              ContainerName: Logstash_ResolvConf_InitContainer
          Essential: true
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/f-iot-rep:logstash"
          LinuxParameters: {}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: LogGroup
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: ecs
          Name: logstash
      Cpu: "2048"
      ExecutionRoleArn:
        Ref: LogstashTaskExecutionRole
      Family: ecs-logstash
      Memory: "4096"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
    Type: AWS::ECS::TaskDefinition
  LogstashTaskExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Condition: {}
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - Key: com.docker.compose.project
          Value: ecs
        - Key: com.docker.compose.service
          Value: logstash
    Type: AWS::IAM::Role
