AWSTemplateFormatVersion: "2010-09-09"
Description: Network
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  VpcCidrBlock:
    Type: String
    Default: 172.31.0.0/16

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  # VPC
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref AWS::StackName, VPC]]
  # Gateway
  # InternetGateway:
  #   Type: AWS::EC2::InternetGateway
  #   Properties:
  #     Tags:
  #       - Key: Name
  #         Value: !Join [" ", [!Ref AWS::StackName, InternetGateway]]
  # InternetGatewayAttachment:
  #   Type: AWS::EC2::VPCGatewayAttachment
  #   Properties:
  #     InternetGatewayId: !Ref InternetGateway
  #     VpcId: !Ref Vpc
  # Subnet
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: Vpc
      CidrBlock: !Select
        - 0
        - Fn::Cidr: [!GetAtt Vpc.CidrBlock, 3, 12]
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      # MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref AWS::StackName, PublicSubnet1]]
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: Vpc
      CidrBlock: !Select
        - 1
        - Fn::Cidr: [!GetAtt Vpc.CidrBlock, 3, 12]
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      # MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref AWS::StackName, PublicSubnet2]]
  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: Vpc
      CidrBlock: !Select
        - 2
        - Fn::Cidr: [!GetAtt Vpc.CidrBlock, 3, 12]
      AvailabilityZone: !Select
        - 2
        - Fn::GetAZs: !Ref AWS::Region
      # MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref AWS::StackName, PublicSubnet3]]
  # RoutTable
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref AWS::StackName, RouteTable]]
  # Route:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref RouteTable
  #     DestinationCidrBlock: 0.0.0.0/0
  #     GatewayId: !Ref InternetGateway
  # SubnetRoutTableAssociation
  PublicSubnet1RootTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref RouteTable
  PublicSubnet2RootTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref RouteTable
  PublicSubnet3RootTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet3
      RouteTableId: !Ref RouteTable

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  VpcId:
    Value:
      Ref: Vpc
  PublicSubnet1Id:
    Value:
      Ref: PublicSubnet1
  PublicSubnet2Id:
    Value:
      Ref: PublicSubnet2
  PublicSubnet3Id:
    Value:
      Ref: PublicSubnet3
  RouteTableId:
    Value:
      Ref: RouteTable
