AWSTemplateFormatVersion: "2010-09-09"
Description: ALB
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  NlbName:
    Type: String
    Default: f-iot-nlb
  NlbForLogstashTargetGroupName:
    Type: String
    Default: nlb-for-logstash-tg
  NlbForAlbTargetGroupName:
    Type: String
    Default: nlb-for-alb-tg
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: String
  AlbId:
    Type: String

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  Nlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Ref NlbName
      Scheme: internal
      SubnetMappings:
        - SubnetId: !Select [0, !Split [",", !Ref SubnetIds]]
        - SubnetId: !Select [1, !Split [",", !Ref SubnetIds]]
        - SubnetId: !Select [2, !Split [",", !Ref SubnetIds]]
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref AWS::StackName, Nlb]]
      Type: network

  NlbForLogstashTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: 5044
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      IpAddressType: ipv4
      Name: !Ref NlbForLogstashTargetGroupName
      Port: 5044
      Protocol: TCP
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref AWS::StackName, NlbForLogstashTargetGroup]]
      TargetType: ip
      VpcId: !Ref VpcId

  NlbForLogstashListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbForLogstashTargetGroup
      LoadBalancerArn: !Ref Nlb
      Port: 5044
      Protocol: TCP

  NlbForAlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 6
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      IpAddressType: ipv4
      Name: !Ref NlbForAlbTargetGroupName
      Port: 80
      Protocol: TCP
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref AWS::StackName, NlbForAlbTargetGroup]]
      Targets:
        - Id: !Ref AlbId
          Port: 80
      TargetType: alb
      VpcId: !Ref VpcId

  NlbForAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbForAlbTargetGroup
      LoadBalancerArn: !Ref Nlb
      Port: 80
      Protocol: TCP

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  NlbId:
    Value:
      Ref: Nlb
  NlbTargetGroupId:
    Value:
      Ref: NlbForLogstashTargetGroup
