AWSTemplateFormatVersion: "2010-09-09"
Description: OpenSearchServiceDomain resource
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  DomainName:
    Description: User-defined OpenSearch domain name
    Type: String
    Default: my-es
  EngineVersion:
    Description: User-defined OpenSearch version
    Type: String
    Default: OpenSearch_1.1
  InstanceType:
    Type: String
    Default: t3.small.search
  SubnetIds:
    Type: String
  SecurityGroupId:
    Type: String

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  # OpenSearchServiceDomain
  OpenSearchServiceDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Ref DomainName
      EngineVersion: !Ref EngineVersion
      ClusterConfig:
        InstanceCount: 3
        InstanceType: !Ref InstanceType
        DedicatedMasterEnabled: true
        DedicatedMasterType: !Ref InstanceType
        DedicatedMasterCount: 3
        ZoneAwarenessEnabled: true
        ZoneAwarenessConfig:
          AvailabilityZoneCount: 3
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: 9b75607c-8ff7-48eb-9735-dc64340759a7
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${DomainName}/*"
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: true
      VPCOptions:
        SubnetIds: !Split [",", !Ref SubnetIds]
        SecurityGroupIds:
          - !Ref SecurityGroupId
      Tags:
        - Key: f-iot.opensearch.service
          Value: OpenSearch

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  Arn:
    Value: !GetAtt OpenSearchServiceDomain.Arn
  DomainEndpoint:
    Value: !GetAtt OpenSearchServiceDomain.DomainEndpoint
