AWSTemplateFormatVersion: "2010-09-09"
Description: Security Group
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcCidrBlock:
    Type: String
    Default: 172.31.0.0/16

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  # SecurityGroup
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref "AWS::StackName", SecurityGroup, EC2]]
  SecurityGroupSSHinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
  SecurityGroupHTTPoutbound:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: !Ref VpcCidrBlock
  SecurityGroupTCPoutbound:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 5044
      ToPort: 5044
      CidrIp: !Ref VpcCidrBlock
  # OpenSearchSecurityGroup
  OpenSearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Opensearch
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref "AWS::StackName", SecurityGroup, OpenSearch]]
  OpenSearchSecurityGroupHTTPSinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref OpenSearchSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: !Ref VpcCidrBlock
  OpenSearchSecurityGroupHTTPSoutbound:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref OpenSearchSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: !Ref VpcCidrBlock
  # VpcEndpointSecurityGroup
  VpcEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for VpcEndpoint
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value:
            !Join [" ", [!Ref "AWS::StackName", SecurityGroup, VpcEndpoint]]
  VpcEndpointSecurityGroupHTTPSinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref VpcEndpointSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: !Ref VpcCidrBlock
  VpcEndpointSecurityGroupHTTPSoutbound:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref VpcEndpointSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: !Ref VpcCidrBlock
  # FargateSecurityGroup
  FargateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Fargate
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref "AWS::StackName", SecurityGroup, Fargate]]
  FargateSecurityGroupTCPinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref FargateSecurityGroup
      IpProtocol: tcp
      FromPort: 5044
      ToPort: 5044
      CidrIp: !Ref VpcCidrBlock
  FargateSecurityGroupHTTPSoutbound:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref FargateSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0
  FargateSecurityGroupDNSoutbound:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref FargateSecurityGroup
      IpProtocol: tcp
      FromPort: 53
      ToPort: 53
      CidrIp: !Ref VpcCidrBlock
  # AlbSecurityGroup
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Alb
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Join [" ", [!Ref "AWS::StackName", SecurityGroup, Alb]]
  AlbSecurityGroupHTTPinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref AlbSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: !Ref VpcCidrBlock
  AlbSecurityGroupHTTPSoutbound:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref AlbSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: !Ref VpcCidrBlock

# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
Outputs:
  SecurityGroupId:
    Value: !Ref SecurityGroup
  OpenSearchSecurityGroupId:
    Value: !Ref OpenSearchSecurityGroup
  VpcEndpointSecurityGroupId:
    Value: !Ref VpcEndpointSecurityGroup
  FargateSecurityGroupId:
    Value: !Ref FargateSecurityGroup
  AlbSecurityGroupId:
    Value: !Ref AlbSecurityGroup
