AWSTemplateFormatVersion: "2010-09-09"
Description: VPC FlowLog
# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
Resources:
  VpcFlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt VpcFlowLogRole.Arn
      LogDestinationType: cloud-watch-logs
      LogGroupName: !Ref LogGroupName
      ResourceId: !Ref VpcId
      ResourceType: VPC
      TrafficType: ALL
  VpcFlowLogRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Condition: {}
            Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: VpcFlowLogAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                Resource: "*"
      Tags:
        - Key: name
          Value: flow-log
    Type: AWS::IAM::Role

  VpcFlowLogGroupName:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
